vi.mock('@/App',()=>({useAuth:()=>({hasPermission:()=>true,permissionsReady:true})}));
import {render,screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {it,expect,vi} from 'vitest';
import {NewItemForm} from './inventory';
it('encadena área y agrupamiento y limpia la categoría al cambiar de área',async()=>{
 const user=userEvent.setup();const submit=vi.fn();
 const categories=[{id:'g',name:'Grupo SPA',area:'spa',isGroup:true,isActive:'true'},{id:'s',name:'Sub SPA',area:'spa',parentId:'g',isGroup:false,isActive:'true'},{id:'r',name:'Sub Restaurant',area:'restaurant',isGroup:false,isActive:'true'},{id:'x',name:'Inactiva',area:'spa',parentId:'g',isGroup:false,isActive:'false'}];
 render(<QueryClientProvider client={new QueryClient()}><NewItemForm categories={categories as any} brands={[]} suppliers={[]} existingItems={[]} onSubmit={submit} isPending={false} onCancel={()=>{}}/></QueryClientProvider>);
 await user.click(screen.getByTestId('select-item-area'));await user.click(screen.getByRole('option',{name:'SPA'}));
 await user.click(screen.getByTestId('select-item-group'));await user.click(screen.getByRole('option',{name:'Grupo SPA'}));
 await user.click(screen.getByTestId('select-category'));
 expect(screen.queryByRole('option',{name:'Sub Restaurant'})).toBeNull();expect(screen.queryByRole('option',{name:'Inactiva'})).toBeNull();
 await user.click(screen.getByRole('option',{name:'Sub SPA'}));
 await user.click(screen.getByTestId('select-item-area'));await user.click(screen.getByRole('option',{name:'Restaurante'}));
 expect(screen.getByTestId('select-category')).toHaveTextContent('Seleccionar categoría');
 expect(screen.getByTestId('select-item-group')).toHaveTextContent('Todos los agrupamientos');
 await user.click(screen.getByTestId('select-category'));await user.click(screen.getByRole('option',{name:'Sub Restaurant'}));
 await user.type(screen.getByTestId('input-item-name'),'Artículo');await user.click(screen.getByTestId('button-save-item'));
 expect(submit).toHaveBeenCalledWith(expect.objectContaining({categoryId:'r'}));
});
