import {useState} from 'react';
import {AlertTriangle, PackageOpen} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {InventorySourceReversal} from './inventory-source-reversal';
import {useMutation,useQuery} from '@tanstack/react-query';
import {apiRequest,queryClient} from '@/lib/queryClient';
import {InventoryButton as Button} from './inventory-access';
import {useToast} from '@/hooks/use-toast';
export function InventoryPendingConsumptions({area,readOnly=false,compact=false}:{area?:'restaurant'|'spa';readOnly?:boolean;compact?:boolean}={}){
 const [open,setOpen]=useState(false);
 const {toast}=useToast();const key=['/api/inventory/pending-consumptions',area || 'all'];const {data=[],isError,isLoading}=useQuery<Array<{id:string;source_type:string;source_id:string;error:string;lines:Array<{name?:string;quantity:number;unit?:string}>}>>({queryKey:key,queryFn:async()=>(await apiRequest('GET',key[0]+(area?'?area='+area:''))).json(),refetchInterval:30000});
 const retry=useMutation({mutationFn:async({id,refreshRecipe=false}:{id:string;refreshRecipe?:boolean})=>(await apiRequest('POST',`/api/inventory/pending-consumptions/${id}/retry`,{refreshRecipe})).json(),onSuccess:r=>{queryClient.invalidateQueries({queryKey:[key[0]]});queryClient.invalidateQueries({queryKey:['/api/inventory/items']});queryClient.invalidateQueries({queryKey:['/api/inventory/movements']});toast({title:r.status==='pending'?'El consumo sigue pendiente':'Consumo registrado',description:r.warnings?.[0]?.itemName,variant:r.status==='pending'?'destructive':'default'});},onError:(e:any)=>toast({title:'No se pudo reintentar',description:e.message,variant:'destructive'})});
 const jobs=data.filter(j=>!area || (area==='restaurant'?j.source_type==='restaurant_order':j.source_type.startsWith('spa_')));
 if(isLoading)return null;if(isError)return <p role="alert">No se pudieron consultar los consumos pendientes.</p>;if(!jobs.length)return null;
 const content=<div className="space-y-4"><p className="text-sm leading-relaxed text-muted-foreground">Las ventas y servicios están guardados. Estos consumos todavía no descontaron stock; revisá la receta, las existencias, el depósito y las equivalencias antes de reintentar.</p>{readOnly&&<a className="text-sm text-primary underline" href="/inventory">Revisar en Inventario</a>}{jobs.map(job=>{
 const areaLabel=job.source_type==='restaurant_order'?'Restaurant':job.source_type==='spa_account'?'Tratamiento SPA':'Producto SPA';
 const names=[...new Set(job.lines.map(l=>l.name).filter(Boolean))];
 const reason=/receta|vincular/i.test(job.error||'')?'Revisar receta':/equivalencia|unidad/i.test(job.error||'')?'Revisar unidades':/depósito/i.test(job.error||'')?'Revisar stock y depósito':'Revisar consumo';
 return <article key={job.id} className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="flex gap-3 p-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-400"><PackageOpen className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-medium text-muted-foreground">{areaLabel}</span><span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-800 dark:bg-amber-950 dark:text-amber-300">{reason}</span></div><h3 className="mt-1 font-semibold">{names.length?names.join(', '):'Consumo pendiente'}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{job.error}</p><details className="mt-2 text-xs text-muted-foreground"><summary className="cursor-pointer">Referencia de la operación</summary><p className="mt-1 break-all">{job.source_id}</p></details></div></div>{!readOnly&&<div className="flex flex-wrap gap-2 border-t bg-muted/30 p-3"><Button permission="operate" size="sm" disabled={retry.isPending} onClick={()=>retry.mutate({id:job.id})}>Reintentar consumo</Button>{job.source_type==='restaurant_order'&&job.lines.some(l=>!(l as any).itemId)&&<Button permission="operate" size="sm" variant="outline" disabled={retry.isPending} onClick={()=>{if(window.confirm('¿Recalcular los consumos de este pedido con la receta actual y reintentar? Se conservará el historial de esta modificación.'))retry.mutate({id:job.id,refreshRecipe:true});}}>Usar receta actual</Button>}<InventorySourceReversal pending sourceType={job.source_type} sourceId={job.source_id}/></div>}</article>;
 })}</div>;
 if(!compact)return <section className="rounded-xl border border-amber-300 bg-card p-4 space-y-3"><h3 className="font-semibold">Consumos pendientes de stock ({jobs.length}{jobs.length===500?'+':''})</h3>{content}</section>;
 return <><Button variant="outline" onClick={()=>setOpen(true)} className="border-amber-300 text-amber-800 hover:bg-amber-50 dark:border-amber-800 dark:text-amber-300 dark:hover:bg-amber-950"><AlertTriangle className="mr-2 h-4 w-4"/>Pendientes de stock<span className="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-xs font-semibold dark:bg-amber-950">{jobs.length}{jobs.length===500?'+':''}</span></Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[85vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-500"/>Pendientes de stock</DialogTitle><DialogDescription>{jobs.length} consumos por revisar</DialogDescription></DialogHeader>{content}</DialogContent></Dialog></>;
}
