import {useState} from 'react';
import {Link} from 'wouter';
import {ChevronDown,ChevronUp,Download,Package,Utensils,Sparkles,ClipboardList} from 'lucide-react';
import {InventoryButton as Button} from './inventory-access';
import {initialStockTemplate,INVENTORY_TAXONOMY} from '@shared/inventoryTaxonomy';
import {inventoryAreaLabel} from '@shared/inventoryAreas';
export function InventoryPreparation(){
 const [open,setOpen]=useState(false);
 const download=()=>{const url=URL.createObjectURL(new Blob([initialStockTemplate()],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='plantilla-stock-inicial.csv';link.click();URL.revokeObjectURL(url);};
 return <section className="rounded-xl border bg-card shadow-sm"><button type="button" className="flex w-full items-center justify-between gap-3 p-4 text-left" aria-expanded={open} aria-controls="inventory-preparation" onClick={()=>setOpen(!open)}><span className="flex items-center gap-3"><ClipboardList className="h-5 w-5 text-primary"/><span><span className="block font-semibold">Preparar catálogo y stock inicial</span><span className="block text-sm text-muted-foreground">Qué cargar, dónde y cómo preparar el listado</span></span></span>{open?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{open&&<div id="inventory-preparation" className="space-y-5 border-t p-4"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-lg border p-4"><Package className="mb-2 h-5 w-5 text-primary"/><h3 className="font-medium">Artículos físicos</h3><p className="mt-2 text-sm text-muted-foreground">Ingredientes, bebidas de venta directa, limpieza, blancos y equipamiento se cargan en Inventario. Cada artículo tiene una unidad de stock y la clasificación Área → Agrupamiento → Subagrupamiento.</p></div><div className="rounded-lg border p-4"><Utensils className="mb-2 h-5 w-5 text-primary"/><h3 className="font-medium">Platos y recetas</h3><p className="mt-2 text-sm text-muted-foreground">Creá los platos y sus precios en Recetas y Costos. Vinculá sus ingredientes a los artículos de Inventario. Las elaboraciones almacenadas tienen su propio artículo y se ingresan mediante Producción.</p><Link href="/restaurant/recetas" className="mt-3 inline-block text-sm font-medium text-primary underline">Ir a Recetas y Costos</Link></div><div className="rounded-lg border p-4"><Sparkles className="mb-2 h-5 w-5 text-primary"/><h3 className="font-medium">Tratamientos SPA</h3><p className="mt-2 text-sm text-muted-foreground">Creá el servicio en SPA → Tratamientos. En cada tratamiento definí qué insumos físicos utiliza y en qué cantidades. El tratamiento no tiene stock propio.</p><Link href="/spa" className="mt-3 inline-block text-sm font-medium text-primary underline">Ir a SPA</Link></div></div>
 <div className="rounded-lg bg-muted/40 p-4"><h3 className="font-medium">Listado para la carga inicial</h3><p className="mt-2 text-sm text-muted-foreground">Una fila por artículo y depósito. Indicá la cantidad en su unidad de stock; si comprás cajas o paquetes, agregá su equivalencia. No dupliques un vino por ser también de venta.</p><Button permission="catalog" variant="outline" className="mt-3" onClick={download}><Download className="mr-2 h-4 w-4"/>Descargar plantilla inicial</Button><p className="mt-2 text-xs text-muted-foreground">La plantilla sirve para preparar el listado. Descargarla no importa artículos ni modifica cantidades.</p></div>
 <ol className="list-decimal space-y-2 pl-5 text-sm"><li>Crear los artículos con saldo cero y sus unidades y equivalencias.</li><li>Registrar cada existencia inicial en su depósito, con motivo «Carga inicial», una sola vez.</li><li>Transferir desde recepción al depósito de consumo cuando corresponda. Los consumos automáticos usan el último destino transferido; una entrada sola no establece ese destino.</li><li>Completar recetas e insumos de tratamientos y configurar mínimos por depósito.</li><li>Probar una compra, una transferencia y un consumo antes de operar con stock real.</li></ol>
 <details className="rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">Estructura acordada del inventario físico</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Área</th><th className="p-2">Agrupamiento</th><th className="p-2">Subagrupamientos</th></tr></thead><tbody>{INVENTORY_TAXONOMY.map(branch=><tr key={branch.area+branch.group} className="border-b"><td className="p-2">{inventoryAreaLabel(branch.area)}</td><td className="p-2">{branch.group}</td><td className="p-2">{branch.children.join(' · ')}</td></tr>)}</tbody></table></div></details>
 </div>}</section>;
}
