import {InventorySourceReversal} from './inventory-source-reversal';
import {useMutation,useQuery} from '@tanstack/react-query';
import {apiRequest,queryClient} from '@/lib/queryClient';
import {InventoryButton as Button} from './inventory-access';
import {useToast} from '@/hooks/use-toast';
export function InventoryPendingConsumptions({area,readOnly=false}:{area?:'restaurant'|'spa';readOnly?:boolean}={}){
 const {toast}=useToast();const key=['/api/inventory/pending-consumptions',area || 'all'];const {data=[],isError,isLoading}=useQuery<Array<{id:string;source_type:string;source_id:string;error:string;lines:Array<{name?:string;quantity:number;unit?:string}>}>>({queryKey:key,queryFn:async()=>(await apiRequest('GET',key[0]+(area?'?area='+area:''))).json(),refetchInterval:30000});
 const retry=useMutation({mutationFn:async({id,refreshRecipe=false}:{id:string;refreshRecipe?:boolean})=>(await apiRequest('POST',`/api/inventory/pending-consumptions/${id}/retry`,{refreshRecipe})).json(),onSuccess:r=>{queryClient.invalidateQueries({queryKey:[key[0]]});queryClient.invalidateQueries({queryKey:['/api/inventory/items']});queryClient.invalidateQueries({queryKey:['/api/inventory/movements']});toast({title:r.status==='pending'?'El consumo sigue pendiente':'Consumo registrado',description:r.warnings?.[0]?.itemName,variant:r.status==='pending'?'destructive':'default'});},onError:(e:any)=>toast({title:'No se pudo reintentar',description:e.message,variant:'destructive'})});
 const jobs=data.filter(j=>!area || (area==='restaurant'?j.source_type==='restaurant_order':j.source_type.startsWith('spa_')));
 if(isLoading)return null;if(isError)return <p role="alert">No se pudieron consultar los consumos pendientes.</p>;if(!jobs.length)return null;
 return <section className="border border-amber-500 rounded p-3 space-y-2"><h3 className="font-medium">Consumos pendientes de stock ({jobs.length}{jobs.length===500?'+':''})</h3><p className="text-sm">Las ventas o servicios se conservaron. No se descontó stock de estos consumos. Revisá existencias, depósito y equivalencias antes de reintentar. {readOnly && <a className="underline" href="/inventory">Revisar en Inventario</a>}</p>{jobs.map(job=><div key={job.id} className="border-t pt-2 flex flex-wrap gap-3 justify-between"><div><p>{job.source_type==='restaurant_order'?'Restaurant':job.source_type==='spa_account'?'Tratamiento SPA':'Producto SPA'} · {job.source_id}</p><p className="text-sm text-muted-foreground">{job.error}</p></div>{!readOnly && <><Button permission="operate" disabled={retry.isPending} onClick={()=>retry.mutate({id:job.id})}>Reintentar consumo</Button>{job.source_type==='restaurant_order' && job.lines.some(l=>!(l as any).itemId) && <Button permission="operate" variant="outline" disabled={retry.isPending} onClick={()=>{if(window.confirm('¿Recalcular los consumos de este pedido con la receta actual y reintentar? Se conservará el historial de esta modificación.'))retry.mutate({id:job.id,refreshRecipe:true});}}>Usar receta actual</Button>}<InventorySourceReversal pending sourceType={job.source_type} sourceId={job.source_id}/></>}</div>)}</section>;
}
