import {render,screen,waitFor} from '@testing-library/react';import userEvent from '@testing-library/user-event';import {QueryClient,QueryClientProvider} from '@tanstack/react-query';import {it,expect,vi,beforeEach,afterEach} from 'vitest';
const auth=vi.hoisted(()=>({cost:false}));vi.mock('@/App',()=>({useAuth:()=>({hasPermission:(k:string)=>k.endsWith(':cost')?auth.cost:true})}));
import {InventoryLocations,locationCsv,type InventoryLocation} from './inventory-locations';
const rows:InventoryLocation[]=[{warehouseId:'dst',warehouseName:'Destino',warehouseArea:'spa',itemId:'item',name:'Artículo',sku:'=SKU',unit:'unidad',area:'spa',categoryId:null,itemKind:'venta_directa',stock:'2.000',costPrice:null,minStock:'5.000',criticalStock:'2.000',expected:true,status:'critical',suggestedQuantity:'3.000'},{warehouseId:'src',warehouseName:'Origen',warehouseArea:'spa',itemId:'item',name:'Artículo',sku:'=SKU',unit:'unidad',area:'spa',categoryId:null,itemKind:'venta_directa',stock:'9.000',costPrice:null,minStock:null,criticalStock:null,expected:false,status:'unconfigured',suggestedQuantity:'0.000'}];
const warehouses=[{id:'dst',name:'Destino',is_active:'true'},{id:'src',name:'Origen',is_active:'true'}];
const items=[{id:'item',name:'Artículo',sku:'=SKU',unit:'unidad',isActive:'true',itemKind:'venta_directa'}];
let requests:any[]=[];
beforeEach(()=>{requests=[];auth.cost=false;vi.stubGlobal('fetch',vi.fn(async(url:any,options:any={})=>{requests.push({url:String(url),method:options.method||'GET',body:options.body?JSON.parse(options.body):null});return new Response(JSON.stringify(String(url).includes('/items/item/warehouses')?[{warehouse_id:'src',current_stock:'9'}]:String(url).includes('/locations')?rows:{ok:true}),{status:200});}));});afterEach(()=>vi.unstubAllGlobals());
function mount(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false,queryFn:async({queryKey})=>(await fetch(queryKey.join('/'))).json()}}})}><InventoryLocations warehouses={warehouses} items={items}/></QueryClientProvider>);}
it('cuenta situaciones configuradas y permite ver ubicaciones sin configuración',async()=>{mount();expect(await screen.findByText(/Crítico: 1/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Reponer'})).toBeInTheDocument();expect(screen.queryByRole('columnheader',{name:'Costo'})).toBeNull();await userEvent.selectOptions(screen.getByLabelText('Filtrar estado'),'unconfigured');expect(screen.getByRole('cell',{name:'Origen'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Reponer'})).toBeNull();});
it('precarga destino, artículo y faltante sin ejecutar transferencia',async()=>{mount();await userEvent.click(await screen.findByRole('button',{name:'Reponer'}));expect(screen.getByTestId('select-to-warehouse')).toHaveTextContent('Destino');expect(screen.getByTestId('select-from-warehouse')).toHaveTextContent('Depósito origen');expect(screen.getByTestId('input-transfer-qty-0')).toHaveValue(3);expect(requests.some(r=>r.method==='POST')).toBe(false);});
it('el CSV usa formato argentino, excluye costos sin permiso y neutraliza fórmulas',()=>{const csv=locationCsv(rows.slice(0,1),false);expect(csv).toContain("'=SKU");expect(locationCsv([{...rows[0],sku:'  =FORMULA'}],false)).toContain("'  =FORMULA");expect(csv).not.toContain('Costo unitario');expect(csv).toContain('Crítico');expect(locationCsv([{...rows[0],stock:'1.250'}],false)).toContain('1,25');});
