import {useState,useEffect} from 'react';
import {AlertTriangle,PackageX,Settings2,ShieldCheck,Search,Download,Printer,ArrowDownToLine} from 'lucide-react';
import {Badge} from './ui/badge';
import {useQuery,useMutation} from '@tanstack/react-query';
import {apiRequest,queryClient} from '@/lib/queryClient';
import {InventoryButton as Button,useInventoryPermission} from './inventory-access';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from './ui/dialog';
import {useToast} from '@/hooks/use-toast';
import {TransferForm} from '@/pages/inventory';
export type InventoryLocation={warehouseId:string;warehouseName:string;warehouseArea:string;itemId:string;name:string;sku:string|null;unit:string;area:string|null;categoryId:string|null;itemKind:string;stock:string;costPrice:string|null;minStock:string|null;criticalStock:string|null;expected:boolean;status:string;suggestedQuantity:string};
const number=(n:unknown)=>Number(n).toLocaleString('es-AR',{maximumFractionDigits:3});
const labels:Record<string,string>={zero:'Sin stock',critical:'Crítico',low:'Bajo',ok:'En nivel',unconfigured:'Sin alerta configurada',disabled:'Sin alertas (no se mantiene)'};
export function locationCsv(rows:InventoryLocation[],cost:boolean){
 const cell=(v:unknown)=>{let s=String(v??'');if(/^[\s\u0000-\u001f]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
 const header=['Depósito','SKU','Artículo','Unidad','Stock','Mínimo','Crítico','Estado','Reposición sugerida',...(cost?['Costo unitario']:[])];
 return '\uFEFF'+[header,...rows.map(r=>[r.warehouseName,r.sku,r.name,r.unit,number(r.stock),r.minStock===null?'':number(r.minStock),r.criticalStock===null?'':number(r.criticalStock),labels[r.status],number(r.suggestedQuantity),...(cost?[r.costPrice===null?'':number(r.costPrice)]:[])])].map(row=>row.map(cell).join(';')).join('\r\n');
}
export function InventoryLocations({warehouses,items}:{warehouses:any[];items:any[]}){
 const canCost=useInventoryPermission('cost');const {toast}=useToast();
 const [warehouse,setWarehouse]=useState('all'),[search,setSearch]=useState(''),[status,setStatus]=useState('alerts');
 const [config,setConfig]=useState(false),[wh,setWh]=useState(''),[item,setItem]=useState(''),[min,setMin]=useState('0'),[critical,setCritical]=useState(''),[expected,setExpected]=useState(true);
 const [replenish,setReplenish]=useState<InventoryLocation|null>(null);
 const {data=[],isLoading,isError}=useQuery<InventoryLocation[]>({queryKey:['/api/inventory/locations'],queryFn:async()=>(await apiRequest('GET','/api/inventory/locations')).json(),refetchInterval:30000});
 useEffect(()=>{if(config && wh && item){const row=data.find(r=>r.warehouseId===wh&&r.itemId===item);setMin(row?.minStock??"0");setCritical(row?.criticalStock??"");setExpected(row?.minStock == null ? true : row.expected);}},[wh,item,config]);
 const refresh=()=>{for(const key of ['/api/inventory/locations','/api/inventory/items','/api/inventory/warehouses-summary','/api/inventory/warehouses','/api/inventory/movements'])queryClient.invalidateQueries({queryKey:[key]});};
 const policy=useMutation({mutationFn:()=>apiRequest('PUT',`/api/inventory/locations/${wh}/${item}/policy`,{minStock:min,criticalStock:critical||null,expected}),onSuccess:()=>{refresh();setConfig(false);toast({title:'Límites guardados; las cantidades no cambiaron'});},onError:(e:any)=>toast({title:'No se pudo guardar',description:e.message,variant:'destructive'})});
 const transfer=useMutation({mutationFn:(body:any)=>apiRequest('POST','/api/inventory/transfer',body),onSuccess:()=>{refresh();setReplenish(null);toast({title:'Reposición transferida con historial'});},onError:(e:any)=>toast({title:'No se pudo transferir',description:e.message,variant:'destructive'})});
 const scope=data.filter(r=>(warehouse==='all'||r.warehouseId===warehouse)&&(!search||`${r.name} ${r.sku||''}`.toLowerCase().includes(search.toLowerCase())));
 const rows=scope.filter(r=>status==='all'||(status==='alerts'?['zero','critical','low'].includes(r.status):r.status===status));
 const exportRows=()=>{const url=URL.createObjectURL(new Blob([locationCsv(rows,canCost)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='inventario-por-deposito.csv';a.click();URL.revokeObjectURL(url);};
 const printRows=()=>{
  const popup=window.open('','_blank');
  if(!popup){toast({title:'Permití abrir la ventana para imprimir',variant:'destructive'});return;}
  const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
  const columns=['Depósito','Artículo / SKU','Stock','Mínimo','Crítico','Estado','Reposición',...(canCost?['Costo']:[])];
  popup.document.write(`<!doctype html><html lang="es"><head><title>Stock y alertas</title><style>body{font:12px Arial;color:#172033;padding:20px}table{border-collapse:collapse;width:100%}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}th{background:#f1f5f9}@page{size:A4 landscape;margin:12mm}</style></head><body><h1>Stock y alertas por depósito</h1><p>${escape(warehouse==='all'?'Todos los depósitos':warehouses.find(w=>w.id===warehouse)?.name)} · ${escape(status==='alerts'?'Solo alertas':status==='all'?'Todos los estados':labels[status])}${search?' · '+escape(search):''} · ${rows.length} resultados</p><table><thead><tr>${columns.map(c=>'<th>'+escape(c)+'</th>').join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+[r.warehouseName,r.name+' · '+(r.sku||'Sin SKU'),number(r.stock)+' '+r.unit,r.minStock===null?'—':number(r.minStock),r.criticalStock===null?'—':number(r.criticalStock),labels[r.status],number(r.suggestedQuantity)+' '+r.unit,...(canCost?[r.costPrice===null?'—':number(r.costPrice)]:[])].map(c=>'<td>'+escape(c)+'</td>').join('')+'</tr>').join('')}</tbody></table></body></html>`);
  popup.document.close();popup.focus();popup.print();
 };
 const cards=[
  {key:'zero',title:'Sin stock',icon:PackageX,color:'text-red-600 dark:text-red-400',background:'bg-red-50 dark:bg-red-950/30',description:'Necesitan reposición'},
  {key:'critical',title:'Crítico',icon:AlertTriangle,color:'text-orange-600 dark:text-orange-400',background:'bg-orange-50 dark:bg-orange-950/30',description:'Prioridad de reposición'},
  {key:'low',title:'Bajo',icon:ArrowDownToLine,color:'text-amber-600 dark:text-amber-400',background:'bg-amber-50 dark:bg-amber-950/30',description:'Por debajo del mínimo'},
  {key:'unconfigured',title:'Sin configurar',icon:Settings2,color:'text-slate-600 dark:text-slate-300',background:'bg-slate-100 dark:bg-slate-800',description:'Faltan límites por depósito'},
 ];
 const selectClass='h-10 w-full rounded-md border border-input bg-background px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring';
 return <section className="space-y-5">
 <div><h2 className="text-lg font-semibold">Stock y alertas por depósito</h2><p className="mt-1 text-sm text-muted-foreground">Alertas según los límites definidos para cada depósito.</p></div>
 <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map(card=>{const Icon=card.icon;const count=scope.filter(r=>r.status===card.key).length;return <button key={card.key} type="button" aria-label={`${card.title}: ${isLoading||isError?'no disponible':count}`} aria-pressed={status===card.key} disabled={isLoading||isError} onClick={()=>setStatus(status===card.key?'alerts':card.key)} className={`rounded-xl border bg-card p-4 text-left shadow-sm transition hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${status===card.key?'border-primary ring-1 ring-primary':'border-border'}`}><div className="flex items-center justify-between gap-2"><span className="text-sm font-medium">{card.title}</span><span className={`rounded-lg p-2 ${card.background} ${card.color}`}><Icon className="h-5 w-5"/></span></div><div className={`mt-2 text-3xl font-semibold tabular-nums ${card.color}`}>{isLoading||isError?'—':count}</div><p className="mt-1 text-xs text-muted-foreground">{card.description}</p></button>;})}</div>
 <div className="rounded-xl border bg-card p-4 shadow-sm"><div className="grid gap-4 md:grid-cols-3"><label className="space-y-2 text-sm font-medium"><span>Depósito</span><select className={selectClass} aria-label="Filtrar depósito" value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="all">Todos los depósitos</option>{warehouses.filter(w=>w.is_active!=='false').map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="space-y-2 text-sm font-medium"><span>Artículo o SKU</span><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input aria-label="Buscar artículo o SKU" placeholder="Buscar artículo…" value={search} onChange={e=>setSearch(e.target.value)} className="pl-9"/></div></label><label className="space-y-2 text-sm font-medium"><span>Estado</span><select className={selectClass} aria-label="Filtrar estado" value={status} onChange={e=>setStatus(e.target.value)}><option value="alerts">Solo alertas</option><option value="all">Todos</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><div className="mt-4 flex flex-wrap items-center gap-2 border-t pt-4"><Button variant="outline" onClick={printRows} disabled={isLoading||isError||!rows.length}><Printer className="mr-2 h-4 w-4"/>Imprimir listado</Button><Button variant="outline" onClick={exportRows} disabled={isLoading||isError}><Download className="mr-2 h-4 w-4"/>Exportar filtrado</Button><Button permission="catalog" className="md:ml-auto" onClick={()=>{setWh(warehouse==='all'?'':warehouse);setItem('');setMin('0');setCritical('');setExpected(true);setConfig(true);}}><Settings2 className="mr-2 h-4 w-4"/>Configurar límites</Button></div></div>
 <div className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="flex items-center justify-between border-b px-4 py-3"><h3 className="font-medium">Detalle por depósito</h3><span role="status" className="text-sm text-muted-foreground">{isLoading?'Cargando…':isError?'No disponible':`${rows.length} resultados`}</span></div>
 {isLoading?<p className="p-8 text-center text-muted-foreground">Cargando ubicaciones…</p>:isError?<p role="alert" className="p-8 text-center text-destructive">No se pudieron consultar las ubicaciones.</p>:!rows.length?<div className="flex flex-col items-center px-4 py-10 text-center"><ShieldCheck className="mb-3 h-10 w-10 text-muted-foreground"/><h3 className="font-medium">{status==='alerts'&&!search?'Sin alertas en los depósitos seleccionados':'Sin resultados para estos filtros'}</h3><p className="mt-2 max-w-md text-sm text-muted-foreground">{scope.some(r=>r.status==='unconfigured')?'Hay artículos sin límites definidos. Revisá «Sin configurar» para completar las alertas.':'Probá otro depósito o estado para consultar sus artículos.'}</p><Button variant="outline" className="mt-4" onClick={()=>{setStatus('all');setSearch('');}}>Ver todos los estados</Button></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/50"><tr>{['Depósito','Artículo / SKU','Stock','Mínimo','Crítico','Estado','Reposición',...(canCost?['Costo']:[]),'Acciones'].map(t=><th className="whitespace-nowrap px-4 py-3 text-left font-medium text-muted-foreground" key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.warehouseId+':'+r.itemId} className="border-t hover:bg-muted/30"><td className="px-4 py-4">{r.warehouseName}</td><td className="min-w-40 px-4 py-4 font-medium">{r.name}<div className="mt-1 text-xs font-normal text-muted-foreground">{r.sku||'Sin SKU'}</div></td><td className="whitespace-nowrap px-4 py-4 tabular-nums">{number(r.stock)} {r.unit}</td><td className="px-4 py-4 tabular-nums">{r.minStock===null?'—':number(r.minStock)}</td><td className="px-4 py-4 tabular-nums">{r.criticalStock===null?'—':number(r.criticalStock)}</td><td className="px-4 py-4"><Badge variant="outline" className={r.status==='zero'?'border-red-200 bg-red-50 text-red-700 dark:bg-red-950 dark:text-red-300':r.status==='critical'?'border-orange-200 bg-orange-50 text-orange-700 dark:bg-orange-950 dark:text-orange-300':r.status==='low'?'border-amber-200 bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300':''}>{labels[r.status]}</Badge></td><td className="whitespace-nowrap px-4 py-4 tabular-nums">{number(r.suggestedQuantity)} {r.unit}</td>{canCost&&<td className="px-4 py-4">{r.costPrice===null?'—':number(r.costPrice)}</td>}<td className="px-4 py-4"><div className="flex gap-2"><Button permission="catalog" variant="ghost" onClick={()=>{setWh(r.warehouseId);setItem(r.itemId);setMin(r.minStock??'0');setCritical(r.criticalStock??'');setExpected(r.expected);setConfig(true);}}>Editar límites</Button>{Number(r.suggestedQuantity)>0&&<Button permission="operate" variant="outline" onClick={()=>setReplenish(r)}>Reponer</Button>}</div></td></tr>)}</tbody></table></div>}</div>
 <p className="text-xs text-muted-foreground">Los indicadores cuentan cada artículo en cada depósito. Los artículos sin configurar no generan alertas.</p>
 <Dialog open={config} onOpenChange={setConfig}><DialogContent><DialogHeader><DialogTitle>Artículo que debe mantener el depósito</DialogTitle></DialogHeader><label className="space-y-2 text-sm font-medium">Depósito<select className={selectClass} aria-label="Depósito a configurar" value={wh} onChange={e=>setWh(e.target.value)}><option value="">Seleccionar…</option>{warehouses.filter(w=>w.is_active!=='false').map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="space-y-2 text-sm font-medium">Artículo<select className={selectClass} aria-label="Artículo a configurar" value={item} onChange={e=>setItem(e.target.value)}><option value="">Seleccionar…</option>{items.filter(i=>i.isActive!=='false'&&i.itemKind!=='plato').map(i=><option key={i.id} value={i.id}>{i.name} · {i.sku||'Sin SKU'}</option>)}</select></label><label>Mínimo<Input aria-label="Mínimo por depósito" type="number" min="0" step="0.001" value={min} onChange={e=>setMin(e.target.value)}/></label><label>Crítico (opcional)<Input aria-label="Crítico por depósito" type="number" min="0" step="0.001" value={critical} onChange={e=>setCritical(e.target.value)}/></label><label><input type="checkbox" checked={expected} onChange={e=>setExpected(e.target.checked)}/>Este depósito debe mantener el artículo</label><Button permission="catalog" disabled={!wh||!item||min===''||policy.isPending} onClick={()=>policy.mutate()}>Guardar límites</Button></DialogContent></Dialog>
 <Dialog open={!!replenish} onOpenChange={open=>{if(!open)setReplenish(null);}}><DialogContent><DialogHeader><DialogTitle>Reponer hasta el mínimo</DialogTitle></DialogHeader>{replenish&&<TransferForm key={replenish.warehouseId+replenish.itemId} warehouses={warehouses} items={items} preselectedItem={{item_id:replenish.itemId} as any} preselectedFromWarehouse={null} preselectedToWarehouse={replenish.warehouseId} preselectedQuantity={Number(replenish.suggestedQuantity)} onSubmit={body=>transfer.mutate(body)} isPending={transfer.isPending} onCancel={()=>setReplenish(null)}/>}</DialogContent></Dialog>
 </section>;
}
