import {useState,useEffect} from 'react';
import {useQuery,useMutation} from '@tanstack/react-query';
import {apiRequest,queryClient} from '@/lib/queryClient';
import {InventoryButton as Button,useInventoryPermission} from './inventory-access';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from './ui/dialog';
import {useToast} from '@/hooks/use-toast';
import {TransferForm} from '@/pages/inventory';
export type InventoryLocation={warehouseId:string;warehouseName:string;warehouseArea:string;itemId:string;name:string;sku:string|null;unit:string;area:string|null;categoryId:string|null;itemKind:string;stock:string;costPrice:string|null;minStock:string|null;criticalStock:string|null;expected:boolean;status:string;suggestedQuantity:string};
const number=(n:unknown)=>Number(n).toLocaleString('es-AR',{maximumFractionDigits:3});
const labels:Record<string,string>={zero:'Sin stock',critical:'Crítico',low:'Bajo',ok:'En nivel',unconfigured:'Sin alerta configurada',disabled:'Sin alertas (no se mantiene)'};
export function locationCsv(rows:InventoryLocation[],cost:boolean){
 const cell=(v:unknown)=>{let s=String(v??'');if(/^[\s\u0000-\u001f]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
 const header=['Depósito','SKU','Artículo','Unidad','Stock','Mínimo','Crítico','Estado','Reposición sugerida',...(cost?['Costo unitario']:[])];
 return '\uFEFF'+[header,...rows.map(r=>[r.warehouseName,r.sku,r.name,r.unit,number(r.stock),r.minStock===null?'':number(r.minStock),r.criticalStock===null?'':number(r.criticalStock),labels[r.status],number(r.suggestedQuantity),...(cost?[r.costPrice===null?'':number(r.costPrice)]:[])])].map(row=>row.map(cell).join(';')).join('\r\n');
}
export function InventoryLocations({warehouses,items}:{warehouses:any[];items:any[]}){
 const canCost=useInventoryPermission('cost');const {toast}=useToast();
 const [warehouse,setWarehouse]=useState('all'),[search,setSearch]=useState(''),[status,setStatus]=useState('alerts');
 const [config,setConfig]=useState(false),[wh,setWh]=useState(''),[item,setItem]=useState(''),[min,setMin]=useState('0'),[critical,setCritical]=useState(''),[expected,setExpected]=useState(true);
 const [replenish,setReplenish]=useState<InventoryLocation|null>(null);
 const {data=[],isLoading,isError}=useQuery<InventoryLocation[]>({queryKey:['/api/inventory/locations'],queryFn:async()=>(await apiRequest('GET','/api/inventory/locations')).json(),refetchInterval:30000});
 useEffect(()=>{if(config && wh && item){const row=data.find(r=>r.warehouseId===wh&&r.itemId===item);setMin(row?.minStock??"0");setCritical(row?.criticalStock??"");setExpected(row?.minStock == null ? true : row.expected);}},[wh,item,config]);
 const refresh=()=>{for(const key of ['/api/inventory/locations','/api/inventory/items','/api/inventory/warehouses-summary','/api/inventory/warehouses','/api/inventory/movements'])queryClient.invalidateQueries({queryKey:[key]});};
 const policy=useMutation({mutationFn:()=>apiRequest('PUT',`/api/inventory/locations/${wh}/${item}/policy`,{minStock:min,criticalStock:critical||null,expected}),onSuccess:()=>{refresh();setConfig(false);toast({title:'Límites guardados; las cantidades no cambiaron'});},onError:(e:any)=>toast({title:'No se pudo guardar',description:e.message,variant:'destructive'})});
 const transfer=useMutation({mutationFn:(body:any)=>apiRequest('POST','/api/inventory/transfer',body),onSuccess:()=>{refresh();setReplenish(null);toast({title:'Reposición transferida con historial'});},onError:(e:any)=>toast({title:'No se pudo transferir',description:e.message,variant:'destructive'})});
 const scope=data.filter(r=>(warehouse==='all'||r.warehouseId===warehouse)&&(!search||`${r.name} ${r.sku||''}`.toLowerCase().includes(search.toLowerCase())));
 const rows=scope.filter(r=>status==='all'||(status==='alerts'?['zero','critical','low'].includes(r.status):r.status===status));
 const exportRows=()=>{const url=URL.createObjectURL(new Blob([locationCsv(rows,canCost)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='inventario-por-deposito.csv';a.click();URL.revokeObjectURL(url);};
 return <section className="space-y-4"><h2 className="font-semibold">Stock y alertas por depósito</h2><p className="text-sm text-muted-foreground">Los indicadores cuentan situaciones artículo–depósito. Solo se generan alertas donde se configuró mantener el artículo. Los mínimos generales no se copian automáticamente.</p>
 <div className="flex gap-3 flex-wrap"><label>Depósito <select aria-label="Filtrar depósito" value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="all">Todos los depósitos</option>{warehouses.filter(w=>w.is_active!=='false').map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><Input aria-label="Buscar artículo o SKU" placeholder="Artículo o SKU" value={search} onChange={e=>setSearch(e.target.value)} className="max-w-sm"/><label>Estado <select aria-label="Filtrar estado" value={status} onChange={e=>setStatus(e.target.value)}><option value="alerts">Solo alertas</option><option value="all">Todos</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><Button onClick={exportRows} disabled={isLoading||isError}>Exportar filtrado</Button><Button permission="catalog" onClick={()=>{setWh(warehouse==='all'?'':warehouse);setItem('');setMin('0');setCritical('');setExpected(true);setConfig(true);}}>Configurar artículo y depósito</Button></div>
 <p role="status">{isLoading ? "Cargando alertas…" : isError ? "Alertas no disponibles" : ['zero','critical','low'].map(s=>`${labels[s]}: ${scope.filter(r=>r.status===s).length}`).join(' · ')} · Sin configurar: {scope.filter(r=>r.status==='unconfigured').length}</p>
 {isLoading?<p>Cargando ubicaciones…</p>:isError?<p role="alert">No se pudieron consultar las ubicaciones.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Depósito','Artículo / SKU','Stock','Mínimo','Crítico','Estado','Reposición',...(canCost?['Costo']:[]),'Acciones'].map(t=><th className="text-left p-2" key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.warehouseId+':'+r.itemId} className="border-t"><td className="p-2">{r.warehouseName}</td><td className="p-2">{r.name}<div className="text-muted-foreground">{r.sku||'Sin SKU'}</div></td><td>{number(r.stock)} {r.unit}</td><td>{r.minStock===null?'—':number(r.minStock)}</td><td>{r.criticalStock===null?'—':number(r.criticalStock)}</td><td>{labels[r.status]}</td><td>{number(r.suggestedQuantity)} {r.unit}</td>{canCost&&<td>{r.costPrice===null?'—':number(r.costPrice)}</td>}<td><Button permission="catalog" variant="ghost" onClick={()=>{setWh(r.warehouseId);setItem(r.itemId);setMin(r.minStock??'0');setCritical(r.criticalStock??'');setExpected(r.expected);setConfig(true);}}>Editar límites</Button>{Number(r.suggestedQuantity)>0&&<Button permission="operate" variant="outline" onClick={()=>setReplenish(r)}>Reponer</Button>}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-3">No hay situaciones que coincidan con estos filtros.</p>}</div>}
 <Dialog open={config} onOpenChange={setConfig}><DialogContent><DialogHeader><DialogTitle>Artículo que debe mantener el depósito</DialogTitle></DialogHeader><label>Depósito<select aria-label="Depósito a configurar" value={wh} onChange={e=>setWh(e.target.value)}><option value="">Seleccionar…</option>{warehouses.filter(w=>w.is_active!=='false').map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Artículo<select aria-label="Artículo a configurar" value={item} onChange={e=>setItem(e.target.value)}><option value="">Seleccionar…</option>{items.filter(i=>i.isActive!=='false'&&i.itemKind!=='plato').map(i=><option key={i.id} value={i.id}>{i.name} · {i.sku||'Sin SKU'}</option>)}</select></label><label>Mínimo<Input aria-label="Mínimo por depósito" type="number" min="0" step="0.001" value={min} onChange={e=>setMin(e.target.value)}/></label><label>Crítico (opcional)<Input aria-label="Crítico por depósito" type="number" min="0" step="0.001" value={critical} onChange={e=>setCritical(e.target.value)}/></label><label><input type="checkbox" checked={expected} onChange={e=>setExpected(e.target.checked)}/>Este depósito debe mantener el artículo</label><Button permission="catalog" disabled={!wh||!item||min===''||policy.isPending} onClick={()=>policy.mutate()}>Guardar límites</Button></DialogContent></Dialog>
 <Dialog open={!!replenish} onOpenChange={open=>{if(!open)setReplenish(null);}}><DialogContent><DialogHeader><DialogTitle>Reponer hasta el mínimo</DialogTitle></DialogHeader>{replenish&&<TransferForm key={replenish.warehouseId+replenish.itemId} warehouses={warehouses} items={items} preselectedItem={{item_id:replenish.itemId} as any} preselectedFromWarehouse={null} preselectedToWarehouse={replenish.warehouseId} preselectedQuantity={Number(replenish.suggestedQuantity)} onSubmit={body=>transfer.mutate(body)} isPending={transfer.isPending} onCancel={()=>setReplenish(null)}/>}</DialogContent></Dialog>
 </section>;
}
