vi.mock('@/App',()=>({useAuth:()=>({hasPermission:()=>true,permissionsReady:true})}));
import {render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {QueryClientProvider} from '@tanstack/react-query';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {queryClient} from '@/lib/queryClient';
import {InventoryPendingConsumptions} from './inventory-pending-consumptions';
import {InventorySourceReversal} from './inventory-source-reversal';
import {InventoryUnitConversions} from './inventory-unit-conversions';
vi.mock('@/hooks/use-toast',()=>({useToast:()=>({toast:vi.fn()})}));
let requests:Array<{url:string;method:string;body:any}>=[];
beforeEach(()=>{queryClient.clear();requests=[];vi.stubGlobal('fetch',vi.fn(async(url:any,options:any={})=>{requests.push({url:String(url),method:options.method || 'GET',body:options.body?JSON.parse(options.body):null});const data=String(url).includes('pending-consumptions') && !String(url).includes('/retry') ? [{id:'job',source_type:'spa_account',source_id:'cuenta',error:'Stock insuficiente',lines:[]}] : String(url).includes('unit-conversions') && options.method!=='PUT' ? [] : {status:'completed'};return new Response(JSON.stringify(data),{status:200});}));});
afterEach(()=>vi.unstubAllGlobals());
function mount(element:React.ReactNode){render(<QueryClientProvider client={queryClient}>{element}</QueryClientProvider>);}
it('SPA muestra aviso y acceso a Inventario sin ofrecer acciones de ajuste',async()=>{mount(<InventoryPendingConsumptions area="spa" readOnly/>);expect(await screen.findByText(/Consumos pendientes de stock/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'Revisar en Inventario'})).toHaveAttribute('href','/inventory');expect(screen.queryByRole('button',{name:'Reintentar consumo'})).not.toBeInTheDocument();expect(requests[0].url).toBe('/api/inventory/pending-consumptions?area=spa');});
it('un reintento envía el identificador del pendiente sin crear otra venta',async()=>{mount(<InventoryPendingConsumptions/>);await userEvent.click(await screen.findByRole('button',{name:'Reintentar consumo'}));await waitFor(()=>expect(requests.some(r=>r.method==='POST' && r.url==='/api/inventory/pending-consumptions/job/retry' && r.body.refreshRecipe===false)).toBe(true));});
it('la reversión exige motivo y confirmación del documento completo',async()=>{mount(<InventorySourceReversal sourceType="purchase_invoice" sourceId="123"/>);const user=userEvent.setup();await user.click(screen.getByRole('button',{name:'Revertir stock del documento'}));const confirm=screen.getByRole('button',{name:'Confirmar reversión'});expect(confirm).toBeDisabled();await user.type(screen.getByLabelText('Motivo de reversión'),'Mercadería devuelta');expect(confirm).toBeDisabled();await user.click(screen.getByRole('checkbox'));await user.click(confirm);await waitFor(()=>expect(requests).toEqual(expect.arrayContaining([expect.objectContaining({method:'POST',body:{sourceType:'purchase_invoice',sourceId:'123',reason:'Mercadería devuelta'}})])));});
it('guardar equivalencias envía el factor y la unidad de compra explícitos',async()=>{mount(<InventoryUnitConversions itemId="item" stockUnit="unidad"/>);const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:'Agregar equivalencia'}));await user.type(screen.getByLabelText('Factor de equivalencia 1'),'12');await user.click(screen.getByRole('button',{name:'Guardar equivalencias'}));await waitFor(()=>expect(requests.some(r=>r.method==='PUT' && r.url==='/api/inventory/items/item/unit-conversions' && r.body.conversions[0].fromUnit==='caja' && r.body.conversions[0].factor==='12')).toBe(true));});

it('Inventario mantiene los pendientes detrás del botón y revela acciones y referencia al abrir',async()=>{mount(<InventoryPendingConsumptions compact/>);const trigger=await screen.findByRole('button',{name:/Pendientes de stock/});expect(trigger).toHaveTextContent('1');expect(screen.queryByText('Stock insuficiente')).toBeNull();expect(screen.queryByRole('button',{name:'Reintentar consumo'})).toBeNull();await userEvent.click(trigger);expect(screen.getByRole('dialog')).toBeInTheDocument();expect(screen.getByText('Stock insuficiente')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Reintentar consumo'})).toBeInTheDocument();expect(screen.getByText('cuenta').closest('details')).not.toHaveAttribute('open');});
