import {render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {it,expect,vi,beforeEach,afterEach} from 'vitest';
vi.mock('@/App',()=>({useAuth:()=>({hasPermission:()=>true,permissionsReady:true})}));
import {ProductionStock} from './production-stock';
import {ProductionPreparationEditor} from './production-preparation-editor';
import {ProductionTab} from './production-tab';
import RecetasCostosPage from '@/pages/recetas-costos';
const formula={recipeId:'prep',name:'Sorrentinos',productionUnit:'unidad',productionYield:100,outputInventoryItemId:'out',outputItemName:'Sorrentinos',outputUnit:'unidad',outputCurrentStock:999,outputCostPrice:1,categoryId:'cat',notes:'',lines:[{recipeIngredientId:'ing',inventoryItemId:'raw',subRecipeId:null,ingredientName:'Harina',unit:'kg',formulaQuantity:1,merma:0,grossQuantity:1,unitCost:100}]};
const location=(wh:string,name:string,qty:number)=>({warehouseId:wh,warehouseName:name,warehouseArea:'restaurant',itemId:'out',name:'Sorrentinos',sku:'PREP-1',unit:'unidad',area:'restaurant',categoryId:'cat',itemKind:'semielaborado',stock:String(qty),minStock:null,criticalStock:null,expected:false,status:'unconfigured',suggestedQuantity:'0',costPrice:'1'});
let calls:any[]=[];
const fixtures:Record<string,unknown>={'/api/production/formulas':[formula],'/api/inventory/locations':[location('k','Cocina',8),location('f','Freezer',4)],'/api/production/pending':[{request_id:'pending',payload:{recipeId:'prep',outputQuantity:100},error:'Stock insuficiente de Harina'}],'/api/inventory/items':[{id:'raw',name:'Harina',unit:'kg',isActive:'true',itemKind:'materia_prima',costPrice:'100'}],'/api/inventory/categories':[{id:'cat',name:'Pastas',area:'restaurant',isGroup:false,isActive:'true'}],'/api/restaurant/recipes':[], '/api/inventory/warehouses':[{id:'k',name:'Cocina',is_active:'true'}]};
beforeEach(()=>{calls=[];vi.stubGlobal('fetch',vi.fn(async(url:any,options:any={})=>{calls.push({url:String(url),method:options.method||'GET',body:options.body?JSON.parse(options.body):null});return new Response(JSON.stringify(fixtures[String(url)]??(options.method&&options.method!=='GET'?{status:'pending',error:'Stock insuficiente',recipeId:'prep'}:[])),{status:200});}));});afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
function mount(node:React.ReactNode){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false,queryFn:async({queryKey})=>(await fetch(String(queryKey[0]))).json()}}})}>{node}</QueryClientProvider>);}
it('muestra stock por depósito, separado de las producciones pendientes y del saldo global',async()=>{mount(<ProductionStock formulas={[formula]} onProduce={()=>{}}/>);expect(await screen.findByText('8 unidad')).toBeInTheDocument();expect(screen.getByText('4 unidad')).toBeInTheDocument();expect(screen.queryByText('999')).toBeNull();expect(screen.getByText(/Stock insuficiente de Harina/)).toBeInTheDocument();await userEvent.selectOptions(screen.getByLabelText('Depósito de preparaciones'),'k');expect(screen.queryByText('4 unidad')).toBeNull();await userEvent.click(screen.getByRole('button',{name:'Regularizar stock'}));await waitFor(()=>expect(calls.some(c=>c.url==='/api/production/pending/pending/retry'&&c.method==='POST')).toBe(true));});
it('imprime únicamente las existencias del depósito filtrado',async()=>{const write=vi.fn(),print=vi.fn();vi.spyOn(window,'open').mockReturnValue({document:{write,close:vi.fn()},focus:vi.fn(),print} as any);mount(<ProductionStock formulas={[formula]} onProduce={()=>{}}/>);await screen.findByText('8 unidad');await userEvent.selectOptions(screen.getByLabelText('Depósito de preparaciones'),'k');await userEvent.click(screen.getByRole('button',{name:'Imprimir stock'}));expect(write.mock.calls[0][0]).toContain('Cocina');expect(write.mock.calls[0][0]).not.toContain('Freezer');expect(print).toHaveBeenCalledOnce();});
it('crea la fórmula con ingredientes sin registrar una corrida ni cantidades iniciales',async()=>{mount(<ProductionPreparationEditor formulas={[]}/>);await userEvent.click(screen.getByRole('button',{name:'Agregar preparación'}));await userEvent.type(screen.getByLabelText('Nombre de preparación'),'Sorrentinos');await userEvent.type(screen.getByLabelText('Rendimiento esperado'),'100');await waitFor(()=>expect(screen.getByRole('option',{name:/Pastas/})).toBeInTheDocument());await userEvent.selectOptions(screen.getByLabelText('Subagrupamiento de preparación'),'cat');await userEvent.click(screen.getByRole('button',{name:'Agregar ingrediente'}));await userEvent.selectOptions(screen.getByLabelText('Ingrediente 1'),'item:raw');expect(screen.getByLabelText('Unidad 1')).toHaveValue('kg');expect(Array.from((screen.getByLabelText('Unidad 1') as HTMLSelectElement).options).map(o=>o.value)).toEqual(['kg','g']);await userEvent.type(screen.getByLabelText('Cantidad 1'),'1');await userEvent.click(screen.getByRole('button',{name:'Guardar preparación'}));await waitFor(()=>expect(calls.filter(c=>c.method==='POST')).toHaveLength(1));expect(calls.find(c=>c.method==='POST')).toMatchObject({url:'/api/production/preparations',body:{name:'Sorrentinos',unit:'unidad',yield:'100',categoryId:'cat',lines:[{itemId:'raw',quantity:'1',unit:'kg'}]}});expect(calls.some(c=>c.url==='/api/production/runs')).toBe(false);});
it('escala los insumos por recetas planificadas sin confundirlos con el resultado real',async()=>{mount(<ProductionTab/>);await userEvent.click(screen.getByRole('tab',{name:'Registrar producción'}));await userEvent.click(await screen.findByTestId('select-production-formula'));await userEvent.click(screen.getByRole('option',{name:/Sorrentinos/}));const planned=screen.getByLabelText('Recetas planificadas');await userEvent.clear(planned);await userEvent.type(planned,'2');expect(screen.getByTestId('input-production-output-quantity')).toHaveValue(200);await userEvent.clear(screen.getByTestId('input-production-output-quantity'));await userEvent.type(screen.getByTestId('input-production-output-quantity'),'180');expect(planned).toHaveValue(2);});

it('un plato sin ingredientes muestra costo pendiente y no un margen del 100%',async()=>{
 const menu={id:'menu',name:'Plato sin ingredientes',categoryId:'menu-cat',price:'100',isActive:'true'};
 fixtures['/api/restaurant/menu/items']=[menu];fixtures['/api/restaurant/menu/categories']=[{id:'menu-cat',name:'Pastas'}];fixtures['/api/restaurant/recipes']=[{id:'empty',menuItemId:'menu',ingredients:[]}];
 mount(<RecetasCostosPage/>);expect(await screen.findByText('Costo pendiente')).toBeInTheDocument();expect(screen.queryByText('100.0%')).toBeNull();
 fixtures['/api/restaurant/menu/items']=[];fixtures['/api/restaurant/menu/categories']=[];fixtures['/api/restaurant/recipes']=[];
});

it('ofrece los depósitos con el formato real de la API en producción',async()=>{mount(<ProductionTab/>);await userEvent.click(screen.getByRole('tab',{name:'Registrar producción'}));await userEvent.click(await screen.findByTestId('select-production-formula'));await userEvent.click(screen.getByRole('option',{name:/Sorrentinos/}));const triggers=screen.getAllByRole('combobox');await userEvent.click(triggers.find(t=>t.textContent?.includes('Elegir depósito'))!);expect(await screen.findByRole('option',{name:'Cocina'})).toBeInTheDocument();});
