import express from "express";
import http from "node:http";
import {randomUUID} from 'node:crypto';
import pg from 'pg';
import {beforeAll,afterAll,beforeEach,describe,it,expect} from 'vitest';
const suite=process.env.DATABASE_URL?describe:describe.skip;
const prefix='inventory-correction-'+randomUUID();
const pool=process.env.DATABASE_URL?new pg.Pool({connectionString:process.env.DATABASE_URL}):null;
let server:http.Server, base='',role='admin';
async function request(method:string,path:string,body?:object){return fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});}
let correct:typeof import('../inventoryMovementCorrection').correctInventoryMovement;
suite('Correcciones de inventario: stock e historial atómicos',()=>{
 beforeAll(async()=>{if(process.env.NODE_ENV==='production')throw new Error('Solo pruebas');({correctInventoryMovement:correct}=await import('../inventoryMovementCorrection'));await pool!.query("INSERT INTO inventory_warehouses(id,name) VALUES($1,'Depósito prueba')",[prefix]);await pool!.query("INSERT INTO inventory_items(id,name,current_stock) VALUES($1,'Artículo prueba',10)",[prefix]);const {registerInventoryRoutes}=await import('../routes/inventory');const {loadRolePermissionsCache}=await import('../permissions');await loadRolePermissionsCache();const app=express();app.use(express.json());app.use((req,_res,next)=>{req.user={id:prefix,username:'Operador',role} as any;req.isAuthenticated=()=>true;next();});registerInventoryRoutes(app);server=http.createServer(app);await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${(server.address() as any).port}`;});
 beforeEach(async()=>{await pool!.query('DELETE FROM stock_movements WHERE item_id=$1',[prefix]);await pool!.query("UPDATE inventory_items SET current_stock=10,is_active='true' WHERE id=$1",[prefix]);await pool!.query("INSERT INTO stock_movements(id,item_id,movement_type,quantity,previous_stock,new_stock,source_type,created_at) VALUES($1,$2,'entrada',10,0,10,'manual',now())",[prefix,prefix]);});
 afterAll(async()=>{if(server)await new Promise<void>(resolve=>server.close(()=>resolve()));await pool!.query('DELETE FROM stock_movements WHERE item_id=$1',[prefix]);await pool!.query('DELETE FROM audit_logs WHERE entity_id=$1',[prefix]);await pool!.query('DELETE FROM warehouse_stock WHERE item_id=$1',[prefix]);await pool!.query('DELETE FROM inventory_warehouses WHERE id=$1',[prefix]);await pool!.query('DELETE FROM inventory_items WHERE id=$1',[prefix]);await pool!.end();const {pool:p}=await import('../db');await p.end();});
 async function stock(){return (await pool!.query('SELECT current_stock FROM inventory_items WHERE id=$1',[prefix])).rows[0].current_stock;}
 it('anula manteniendo el original y registrando motivo y operador',async()=>{await correct(prefix,'Error de carga','operador');expect(await stock()).toBe('0.000');const rows=(await pool!.query('SELECT * FROM stock_movements WHERE item_id=$1',[prefix])).rows;expect(rows).toHaveLength(2);expect(rows.find(r=>r.source_type==='movement_reversal')).toMatchObject({source_id:prefix,created_by:'operador',notes:'Anulación: Error de carga'});});
 it('corrige con reversión y reemplazo dentro de una operación',async()=>{await correct(prefix,'Cantidad incorrecta','operador',{quantity:'8.125',notes:'Cantidad real'});expect(await stock()).toBe('8.125');expect((await pool!.query('SELECT id FROM stock_movements WHERE item_id=$1',[prefix])).rows).toHaveLength(3);});
 it('no permite doble anulación concurrente',async()=>{const results=await Promise.allSettled([correct(prefix,'Duplicado','operador'),correct(prefix,'Duplicado','operador')]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(await stock()).toBe('0.000');});
 it('bloquea comprobantes y movimientos automáticos',async()=>{await pool!.query("UPDATE stock_movements SET source_type='purchase_invoice',source_id='42' WHERE id=$1",[prefix]);await expect(correct(prefix,'Error','operador')).rejects.toThrow('origen');expect(await stock()).toBe('10.000');});
 it('bloquea la reversión si el stock ya fue consumido',async()=>{await pool!.query('UPDATE inventory_items SET current_stock=3 WHERE id=$1',[prefix]);await expect(correct(prefix,'Error','operador')).rejects.toThrow('negativo');expect(await stock()).toBe('3.000');});
 it('exige motivo y cantidad válida',async()=>{await expect(correct(prefix,' ','operador')).rejects.toThrow('motivo');await expect(correct(prefix,'Error','operador',{quantity:'NaN'})).rejects.toThrow('inválida');expect(await stock()).toBe('10.000');});
 it('revierte también el depósito identificado',async()=>{await pool!.query("INSERT INTO warehouse_stock(warehouse_id,item_id,current_stock) VALUES($1,$1,10)",[prefix]);await pool!.query('UPDATE stock_movements SET warehouse_id=$1 WHERE id=$1',[prefix]);try{await correct(prefix,'Error','operador');expect((await pool!.query('SELECT current_stock FROM warehouse_stock WHERE item_id=$1',[prefix])).rows[0].current_stock).toBe('0.000');}finally{await pool!.query('DELETE FROM warehouse_stock WHERE item_id=$1',[prefix]);}});
 it('edita metadatos sin permitir cambiar cantidades directamente',async()=>{const response=await request('PATCH',`/api/inventory/items/${prefix}/metadata`,{name:'Artículo editado',sku:null,minStock:'2',costPrice:'5',isActive:'true',currentStock:'999'});expect(response.status).toBe(200);expect(await stock()).toBe('10.000');});
 it('la baja exige motivo y conserva stock, artículo y movimientos',async()=>{expect((await request('POST',`/api/inventory/items/${prefix}/deactivate`,{})).status).toBe(400);expect((await request('POST',`/api/inventory/items/${prefix}/deactivate`,{reason:'Discontinuado'})).status).toBe(200);expect((await pool!.query('SELECT is_active FROM inventory_items WHERE id=$1',[prefix])).rows[0].is_active).toBe('false');expect(await stock()).toBe('10.000');expect((await pool!.query('SELECT id FROM stock_movements WHERE item_id=$1',[prefix])).rows).toHaveLength(1);expect((await request('DELETE',`/api/inventory/items/${prefix}`)).status).toBe(405);});
 it('las entradas manuales concurrentes no pierden cantidades',async()=>{const responses=await Promise.all([1,2].map(quantity=>request('POST','/api/inventory/movements',{itemId:prefix,movementType:'entrada',quantity})));expect(responses.map(r=>r.status)).toEqual([201,201]);expect(await stock()).toBe('13.000');});
 it('un usuario sin permiso no puede anular ni dar de baja',async()=>{role='sin_permiso';try{expect((await request('POST',`/api/inventory/movements/${prefix}/anular`,{reason:'Error'})).status).toBe(403);expect((await request('POST',`/api/inventory/items/${prefix}/deactivate`,{reason:'Error'})).status).toBe(403);}finally{role='admin';}expect(await stock()).toBe('10.000');});
 it('una falla de auditoría revierte también stock y registros',async()=>{await pool!.query(`CREATE FUNCTION inventory_correction_test_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.entity_id='${prefix}' THEN RAISE EXCEPTION 'Falla simulada'; END IF; RETURN NEW; END $$`);await pool!.query('CREATE TRIGGER inventory_correction_test_fail BEFORE INSERT ON audit_logs FOR EACH ROW EXECUTE FUNCTION inventory_correction_test_fail()');try{await expect(correct(prefix,'Error','operador')).rejects.toThrow();expect(await stock()).toBe('10.000');expect((await pool!.query('SELECT id FROM stock_movements WHERE item_id=$1',[prefix])).rows).toHaveLength(1);}finally{await pool!.query('DROP TRIGGER inventory_correction_test_fail ON audit_logs');await pool!.query('DROP FUNCTION inventory_correction_test_fail()');}});
});
