import {randomUUID} from 'node:crypto';
import pg from 'pg';
import {beforeAll,beforeEach,afterEach,afterAll,describe,it,expect} from 'vitest';
const suite=process.env.DATABASE_URL?describe:describe.skip;const pool=process.env.DATABASE_URL?new pg.Pool({connectionString:process.env.DATABASE_URL}):null;
let a:string,b:string,w:string,to:string,prefix:string;
let engine:typeof import('../inventoryStockEngine'),safety:typeof import('../inventorySafety'),reversal:typeof import('../inventorySourceReversal');
async function global(id=a){return Number((await pool!.query('SELECT current_stock FROM inventory_items WHERE id=$1',[id])).rows[0].current_stock);}
async function wh(id=to,item=a){return Number((await pool!.query('SELECT current_stock FROM warehouse_stock WHERE warehouse_id=$1 AND item_id=$2',[id,item])).rows[0]?.current_stock || 0);}
suite('Etapa 2: circuito único, unidades y consumos pendientes',()=>{
 beforeAll(async()=>{if(!['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL!).hostname)||process.env.NODE_ENV==='production')throw new Error('Solo base local');engine=await import('../inventoryStockEngine');safety=await import('../inventorySafety');reversal=await import('../inventorySourceReversal');await (await import('../inventoryStage2Schema')).ensureInventoryStage2Schema();});
 beforeEach(async()=>{prefix='stage2-'+randomUUID();a=prefix+'-a';b=prefix+'-b';w=prefix+'-wh';to=prefix+'-to';await pool!.query("INSERT INTO inventory_items(id,name,unit,current_stock,cost_price) VALUES($1,'Harina','kg',14,100),($2,'Aceite','litro',10,50)",[a,b]);await pool!.query("INSERT INTO inventory_warehouses(id,name) VALUES($1,'General'),($2,'Cocina')",[w,to]);await pool!.query('INSERT INTO warehouse_stock(item_id,warehouse_id,current_stock) VALUES($1,$2,10),($3,$2,10)',[a,w,b]);await safety.safeInventoryTransfer(w,to,[{itemId:a,quantity:8},{itemId:b,quantity:5}],undefined,prefix);});
 afterEach(async()=>{await pool!.query('DROP TRIGGER IF EXISTS stage2_fail ON stock_movements');await pool!.query('DROP FUNCTION IF EXISTS stage2_fail()');await pool!.query('DELETE FROM audit_logs WHERE user_id=$1',[prefix]);await pool!.query('DELETE FROM inventory_consumption_jobs WHERE source_id LIKE $1',[prefix+'%']);await pool!.query('DELETE FROM inventory_source_reversals WHERE source_id LIKE $1',[prefix+'%']);await pool!.query('DELETE FROM stock_movements WHERE item_id IN ($1,$2)',[a,b]);await pool!.query('DELETE FROM warehouse_stock WHERE item_id IN ($1,$2)',[a,b]);await pool!.query('DELETE FROM inventory_unit_conversions WHERE item_id IN ($1,$2)',[a,b]);await pool!.query('DELETE FROM item_price_history WHERE item_id IN ($1,$2)',[a,b]);await pool!.query('DELETE FROM inventory_items WHERE id IN ($1,$2)',[a,b]);await pool!.query('DELETE FROM inventory_warehouses WHERE id IN ($1,$2)',[w,to]);});
 afterAll(async()=>{await pool!.end();await (await import('../db')).pool.end();});
 it('convierte gramos a kilos y mantiene el saldo histórico no asignado',async()=>{const r=await engine.queueAutomaticConsumption('restaurant_order',prefix,[{itemId:a,quantity:500,unit:'g'}],prefix);expect(r.status).toBe('completed');expect(await wh()).toBe(7.5);expect(await global()).toBe(13.5);});
 it('falta de stock deja todo pendiente sin descuento parcial',async()=>{const r=await engine.queueAutomaticConsumption('restaurant_order',prefix,[{itemId:a,quantity:1,unit:'kg'},{itemId:b,quantity:99,unit:'litro'}],prefix);expect(r.status).toBe('pending');expect(await wh()).toBe(8);expect(await global()).toBe(14);expect(await wh(to,b)).toBe(5);});
 it('un reintento luego de reponer registra una sola vez',async()=>{const lines=[{itemId:a,quantity:9,unit:'kg'}];expect((await engine.queueAutomaticConsumption('restaurant_order',prefix,lines,prefix)).status).toBe('pending');await safety.safeWarehouseMovement(to,{itemId:a,movementType:'entrada',quantity:2},prefix);expect((await engine.queueAutomaticConsumption('restaurant_order',prefix,lines,prefix)).status).toBe('completed');expect((await engine.queueAutomaticConsumption('restaurant_order',prefix,lines,prefix)).deducted).toHaveLength(0);expect(await wh()).toBe(1);expect(await global()).toBe(7);});
 it('los consumos duplicados simultáneos solo descuentan una vez',async()=>{const results=await Promise.all([1,2].map(()=>engine.queueAutomaticConsumption('spa_account',prefix,[{itemId:a,quantity:2,unit:'kg'}],prefix)));expect(results.map(r=>r.status)).toEqual(['completed','completed']);expect(await wh()).toBe(6);expect(await global()).toBe(12);expect((await pool!.query("SELECT id FROM stock_movements WHERE source_type='spa_account' AND source_id=$1",[prefix])).rows).toHaveLength(1);});
 it('una equivalencia de paquete permite reintentar sin inventar factor',async()=>{const lines=[{itemId:a,quantity:2,unit:'paquete'}];expect((await engine.queueAutomaticConsumption('spa_account',prefix,lines,prefix)).status).toBe('pending');await pool!.query("INSERT INTO inventory_unit_conversions(item_id,from_unit,factor) VALUES($1,'paquete',0.5)",[a]);expect((await engine.queueAutomaticConsumption('spa_account',prefix,lines,prefix)).status).toBe('completed');expect(await global()).toBe(13);});
 it('un depósito sin último destino no se elige silenciosamente',async()=>{await pool!.query("DELETE FROM stock_movements WHERE item_id=$1 AND movement_type='transferencia'",[a]);expect((await engine.queueAutomaticConsumption('spa_account',prefix,[{itemId:a,quantity:1,unit:'kg'}],prefix)).status).toBe('pending');expect(await global()).toBe(14);});
 it('varias líneas del mismo artículo se validan por su suma',async()=>{expect((await engine.queueAutomaticConsumption('restaurant_order',prefix,[{itemId:a,quantity:5,unit:'kg'},{itemId:a,quantity:4,unit:'kg'}],prefix)).status).toBe('pending');expect(await global()).toBe(14);});
 it('revertir un consumo devuelve al mismo depósito y es idempotente',async()=>{await engine.queueAutomaticConsumption('spa_account_item',prefix,[{itemId:a,quantity:2,unit:'kg'}],prefix);expect((await reversal.reverseInventorySource('spa_account_item',prefix,'Producto devuelto físicamente',prefix)).alreadyReversed).toBe(false);expect((await reversal.reverseInventorySource('spa_account_item',prefix,'Reintento',prefix)).alreadyReversed).toBe(true);expect(await global()).toBe(14);expect(await wh()).toBe(8);expect((await engine.queueAutomaticConsumption('spa_account_item',prefix,[{itemId:a,quantity:2}],prefix)).status).toBe('cancelled');});
 it('revertir un pendiente lo cancela sin generar stock ficticio',async()=>{await engine.queueAutomaticConsumption('spa_account_item',prefix,[{itemId:a,quantity:99}],prefix);await reversal.reverseInventorySource('spa_account_item',prefix,'Carga incorrecta',prefix);expect(await global()).toBe(14);expect(await wh()).toBe(8);});
 it('un error SQL no deja saldos ni renglones a medias',async()=>{await pool!.query(`CREATE FUNCTION stage2_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.item_id='${b}' THEN RAISE EXCEPTION 'Falla simulada'; END IF; RETURN NEW; END $$`);await pool!.query('CREATE TRIGGER stage2_fail BEFORE INSERT ON stock_movements FOR EACH ROW EXECUTE FUNCTION stage2_fail()');await expect(engine.queueAutomaticConsumption('restaurant_order',prefix,[{itemId:a,quantity:1,unit:'kg'},{itemId:b,quantity:1,unit:'litro'}],prefix)).rejects.toThrow();expect(await global()).toBe(14);expect(await wh()).toBe(8);expect((await pool!.query('SELECT id FROM inventory_consumption_jobs WHERE source_id=$1',[prefix])).rows).toHaveLength(0);});
 it('la corrección de un ajuste usa el saldo del depósito, no el global',async()=>{await safety.safeWarehouseMovement(to,{itemId:a,movementType:'ajuste',quantity:6},prefix);const rows=await pool!.query("SELECT id FROM stock_movements WHERE item_id=$1 AND movement_type='ajuste' ORDER BY created_at DESC LIMIT 1",[a]);await (await import('../inventoryMovementCorrection')).correctInventoryMovement(rows.rows[0].id,'Conteo revisado',prefix,{quantity:'7'});expect(await wh()).toBe(7);expect(await global()).toBe(13);});
});
