import {randomUUID} from 'node:crypto';
import http from 'node:http';
import express from 'express';
import pg from 'pg';
import {beforeAll,beforeEach,afterEach,afterAll,describe,it,expect} from 'vitest';
const suite=process.env.DATABASE_URL?describe:describe.skip;
const pool=process.env.DATABASE_URL?new pg.Pool({connectionString:process.env.DATABASE_URL}):null;
let prefix:string,item:string,out:string,warehouse:string,recipe:string,ingredient:string,account:string,order:string,menu:string,category:string;
let server:http.Server,url:string,role='admin';
async function request(method:string,path:string,body?:unknown){const r=await fetch(url+path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();return {status:r.status,body:t?(r.headers.get("content-type")?.includes("json")?JSON.parse(t):{error:t}):null};}
suite('Etapa 2: formularios y operaciones reales aisladas',()=>{
 beforeAll(async()=>{if(!['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL!).hostname))throw new Error('Solo local');await (await import('../permissions')).loadRolePermissionsCache();const app=express();app.use(express.json());app.use((req,_res,next)=>{req.user={id:'stage2-workflows',username:'stage2-workflows',fullName:'Prueba',role} as any;req.isAuthenticated=()=>true;next();});await (await import('../inventoryStage2Schema')).ensureInventoryStage2Schema();(await import('../routes/inventory')).registerInventoryRoutes(app);(await import('../routes/spa')).registerSpaRoutes(app);(await import('../routes/production')).registerProductionRoutes(app);server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+(server.address() as any).port;});
 beforeEach(async()=>{prefix='workflows-'+randomUUID();item=prefix+'-item';out=prefix+'-out';warehouse=prefix+'-wh';recipe=prefix+'-recipe';ingredient=prefix+'-ing';account=prefix+'-account';order=prefix+'-order';menu=prefix+'-menu';category=prefix+'-category';
  await pool!.query("INSERT INTO inventory_items(id,name,unit,current_stock,cost_price,item_kind) VALUES($1,'Materia prima','kg',5,100,'materia_prima'),($2,'Elaborado','kg',0,0,'semielaborado')",[item,out]);await pool!.query("INSERT INTO inventory_warehouses(id,name) VALUES($1,'Destino')",[warehouse]);await pool!.query('INSERT INTO warehouse_stock(item_id,warehouse_id,current_stock) VALUES($1,$2,5)',[item,warehouse]);await pool!.query("INSERT INTO stock_movements(item_id,movement_type,quantity,previous_stock,new_stock,to_warehouse_id,created_at) VALUES($1,'transferencia',5,0,5,$2,now())",[item,warehouse]);
  await pool!.query("INSERT INTO recipes(id,name,is_base,production_unit,production_yield,output_inventory_item_id) VALUES($1,'Fórmula',true,'kg',2,$2)",[recipe,out]);await pool!.query("INSERT INTO recipe_ingredients(id,recipe_id,inventory_item_id,ingredient_name,quantity,unit,unit_cost) VALUES($1,$2,$3,'Materia prima',500,'g',0.1)",[ingredient,recipe,item]);await pool!.query("INSERT INTO spa_accounts(id,appointment_id,guest_name,status,opened_at) VALUES($1,$2,'Prueba','open',now())",[account,prefix+'-appointment']);
 });
 afterEach(async()=>{role='admin';await pool!.query("DELETE FROM audit_logs WHERE user_id='stage2-workflows'");await pool!.query('DELETE FROM inventory_production_requests WHERE request_id LIKE $1',[prefix+'%']);await pool!.query("DELETE FROM inventory_source_reversals WHERE actor='stage2-workflows' OR source_id LIKE $1",[prefix+'%']);await pool!.query('DELETE FROM inventory_consumption_jobs WHERE source_id LIKE $1 OR lines::text LIKE $2',[prefix+'%','%'+item+'%']);await pool!.query('DELETE FROM stock_movements WHERE item_id IN($1,$2)',[item,out]);await pool!.query('DELETE FROM production_runs WHERE recipe_id=$1',[recipe]);await pool!.query('DELETE FROM recipe_ingredients WHERE recipe_id=$1',[recipe]);await pool!.query('DELETE FROM recipes WHERE id=$1',[recipe]);await pool!.query('DELETE FROM order_items WHERE order_id=$1',[order]);await pool!.query('DELETE FROM restaurant_orders WHERE id=$1',[order]);await pool!.query('DELETE FROM menu_items WHERE id=$1',[menu]);await pool!.query('DELETE FROM menu_categories WHERE id=$1',[category]);await pool!.query("DELETE FROM folio_movements WHERE folio_id IN(SELECT id FROM folios WHERE entity_id=$1)",[account]);await pool!.query('DELETE FROM folios WHERE entity_id=$1',[account]);await pool!.query('DELETE FROM spa_account_items WHERE account_id=$1',[account]);await pool!.query('DELETE FROM spa_accounts WHERE id=$1',[account]);await pool!.query('DELETE FROM warehouse_stock WHERE item_id IN($1,$2)',[item,out]);await pool!.query('DELETE FROM inventory_unit_conversions WHERE item_id IN($1,$2)',[item,out]);await pool!.query('DELETE FROM inventory_items WHERE id IN($1,$2)',[item,out]);await pool!.query('DELETE FROM inventory_warehouses WHERE id=$1',[warehouse]);});
 afterAll(async()=>{await new Promise<void>(r=>server.close(()=>r()));await pool!.end();await (await import('../db')).pool.end();});
 it('cargar receta para consumo interno convierte gramos a kilos sin mover stock',async()=>{const r=await request('POST','/api/inventory/recipe-stock-preview',{recipeId:recipe,multiplier:3});expect(r.status,JSON.stringify(r.body)).toBe(200);expect(r.body).toEqual([{itemId:item,quantity:'1.500',notes:''}]);expect(Number((await pool!.query('SELECT current_stock FROM inventory_items WHERE id=$1',[item])).rows[0].current_stock)).toBe(5);});
 it('configurar cajas actualiza costos de receta y conserva cantidades',async()=>{await pool!.query("UPDATE recipe_ingredients SET unit='caja',quantity=1 WHERE id=$1",[ingredient]);const r=await request('PUT',`/api/inventory/items/${item}/unit-conversions`,{conversions:[{fromUnit:'caja',factor:2}]});expect(r.status,JSON.stringify(r.body)).toBe(200);expect(Number((await pool!.query('SELECT unit_cost FROM recipe_ingredients WHERE id=$1',[ingredient])).rows[0].unit_cost)).toBe(200);expect(Number((await pool!.query('SELECT current_stock FROM inventory_items WHERE id=$1',[item])).rows[0].current_stock)).toBe(5);});
 it('si falta equivalencia la vista previa rechaza en vez de usar cajas como kilos',async()=>{await pool!.query("UPDATE recipe_ingredients SET unit='caja',quantity=1 WHERE id=$1",[ingredient]);const r=await request('POST','/api/inventory/recipe-stock-preview',{recipeId:recipe,multiplier:1});expect(r.status).toBe(409);expect(r.body.error).toMatch(/equivalencia/);});
 it('un producto SPA sin stock conserva cargo y folio, y un reintento descontará una sola vez',async()=>{const r=await request('POST',`/api/spa/accounts/${account}/items`,{description:'Producto',quantity:8,unitPrice:'100',itemType:'product',inventoryItemId:item});expect(r.status,JSON.stringify(r.body)).toBe(201);const jobs=await pool!.query('SELECT * FROM inventory_consumption_jobs WHERE source_id=$1',[r.body.id]);expect(jobs.rows[0].status).toBe('pending');expect((await pool!.query("SELECT amount FROM folio_movements WHERE source_type='spa_item' AND source_id=$1",[r.body.id])).rows).toMatchObject([{amount:'800.00'}]);expect((await request('DELETE',`/api/spa/account-items/${r.body.id}`)).status).toBe(409);await (await import('../inventorySafety')).safeWarehouseMovement(warehouse,{itemId:item,movementType:'entrada',quantity:5},'stage2-workflows');expect((await request('POST',`/api/inventory/pending-consumptions/${jobs.rows[0].id}/retry`,{})).body.status).toBe('completed');expect((await request('POST',`/api/inventory/pending-consumptions/${jobs.rows[0].id}/retry`,{})).body.status).toBe('completed');expect(Number((await pool!.query('SELECT current_stock FROM inventory_items WHERE id=$1',[item])).rows[0].current_stock)).toBe(2);});
 it('una receta corregida permite resolver un pedido pendiente sin duplicar operaciones',async()=>{await pool!.query("INSERT INTO menu_categories(id,name) VALUES($1,'Prueba')",[category]);await pool!.query("INSERT INTO menu_items(id,category_id,name,price) VALUES($1,$2,'Plato',100)",[menu,category]);await pool!.query("INSERT INTO restaurant_orders(id,order_number,status,order_type,total,opened_at) VALUES($1,$2,'closed','dine_in',200,now())",[order,prefix]);await pool!.query('INSERT INTO order_items(order_id,menu_item_id,quantity,unit_price,subtotal) VALUES($1,$2,2,100,200)',[order,menu]);const storage=(await import('../db-storage')).storage;expect((await storage.deductStockFromOrder(order,await storage.getOrderItems(order),'stage2-workflows')).status).toBe('pending');await pool!.query('UPDATE recipes SET menu_item_id=$1,is_base=false WHERE id=$2',[menu,recipe]);const job=(await pool!.query('SELECT id FROM inventory_consumption_jobs WHERE source_id=$1',[order])).rows[0];const r=await request('POST',`/api/inventory/pending-consumptions/${job.id}/retry`,{refreshRecipe:true});expect(r.status,JSON.stringify(r.body)).toBe(200);expect(r.body.status).toBe('completed');expect(Number((await pool!.query('SELECT current_stock FROM inventory_items WHERE id=$1',[item])).rows[0].current_stock)).toBe(4);expect((await pool!.query("SELECT id FROM audit_logs WHERE entity_id=$1 AND action='update' AND description='Consumo pendiente recalculado con la receta actual'",[job.id])).rows).toHaveLength(1);});
 it('dos solicitudes de producción con el mismo identificador generan una corrida',async()=>{const payload={date:'2026-10-07',recipeId:recipe,requestId:prefix+'-request',outputQuantity:2,outputWarehouseId:warehouse,lines:[{recipeIngredientId:ingredient,actualQuantity:500,warehouseId:warehouse}]};const r=await Promise.all([1,2].map(()=>request('POST','/api/production/runs',payload)));expect(r.map(v=>v.status),JSON.stringify(r)).toEqual([201,201]);expect(r[0].body.run.id).toBe(r[1].body.run.id);expect(Number((await pool!.query('SELECT current_stock FROM inventory_items WHERE id=$1',[item])).rows[0].current_stock)).toBe(4.5);expect(Number((await pool!.query('SELECT current_stock FROM inventory_items WHERE id=$1',[out])).rows[0].current_stock)).toBe(2);expect((await request('POST','/api/production/runs',{...payload,outputQuantity:3})).status).toBe(400);});
 it('una subreceta producida consume el elaborado y transmite su costo real',async()=>{
  await pool!.query('UPDATE inventory_items SET current_stock=2,cost_price=80 WHERE id=$1',[out]);
  await pool!.query('INSERT INTO warehouse_stock(item_id,warehouse_id,current_stock) VALUES($1,$2,2)',[out,warehouse]);
  await pool!.query("INSERT INTO stock_movements(item_id,movement_type,quantity,previous_stock,new_stock,to_warehouse_id,created_at) VALUES($1,'transferencia',2,0,2,$2,now())",[out,warehouse]);
  const parent=prefix+'-parent';const ing=prefix+'-parenting';
  try{await pool!.query("INSERT INTO recipes(id,name,is_base) VALUES($1,'Plato',false)",[parent]);await pool!.query("INSERT INTO recipe_ingredients(id,recipe_id,sub_recipe_id,ingredient_name,quantity,unit,unit_cost) VALUES($1,$2,$3,'Elaborado',250,'g',0)",[ing,parent,recipe]);
   const r=await request('POST','/api/inventory/recipe-stock-preview',{recipeId:parent,multiplier:2});expect(r.status).toBe(200);expect(r.body).toEqual([{itemId:out,quantity:'0.500',notes:''}]);
   const {db,withDatabaseTransaction}=await import('../db');await withDatabaseTransaction(()=> (import('../recipeCostCascade')).then(m=>m.cascadeRecipeCostsFromInventoryItem(db,out,80)));
   expect(Number((await pool!.query('SELECT unit_cost FROM recipe_ingredients WHERE id=$1',[ing])).rows[0].unit_cost)).toBe(0.08);
  }finally{await pool!.query('DELETE FROM recipe_ingredients WHERE id=$1',[ing]);await pool!.query('DELETE FROM recipes WHERE id=$1',[parent]);}
 });
 it('impide cambiar cantidades o la unidad base por edición directa',async()=>{
  expect((await request('PATCH',`/api/inventory/items/${item}`,{currentStock:99})).status).toBe(409);
  expect((await request('PATCH',`/api/inventory/items/${item}`,{unit:'g'})).status).toBe(409);
  expect(Number((await pool!.query('SELECT current_stock FROM inventory_items WHERE id=$1',[item])).rows[0].current_stock)).toBe(5);
 });
 it('cancelar un cargo SPA pendiente conserva la trazabilidad y anula su efecto en el folio',async()=>{
  const charge=await request('POST',`/api/spa/accounts/${account}/items`,{description:'Producto incorrecto',quantity:8,unitPrice:'100',inventoryItemId:item,itemType:'product'});expect(charge.status).toBe(201);
  expect((await request('POST','/api/inventory/source-stock-reversals',{sourceType:'spa_account_item',sourceId:charge.body.id,reason:'Carga incorrecta'})).status).toBe(200);
  expect((await request('DELETE',`/api/spa/account-items/${charge.body.id}`)).status).toBe(204);
  const ledger=await pool!.query('SELECT type,amount FROM folio_movements WHERE folio_id IN(SELECT id FROM folios WHERE entity_id=$1) ORDER BY type',[account]);
  expect(ledger.rows).toEqual([{type:'charge',amount:'800.00'},{type:'void',amount:'800.00'}]);
  expect((await pool!.query('SELECT balance FROM folios WHERE entity_id=$1',[account])).rows[0].balance).toBe('0.00');
  expect(Number((await pool!.query('SELECT current_stock FROM inventory_items WHERE id=$1',[item])).rows[0].current_stock)).toBe(5);
 });
 it('un usuario sin permiso no puede reintentar, revertir ni cambiar equivalencias',async()=>{role='sin_permiso';for(const [method,path,body] of [['POST','/api/inventory/source-stock-reversals',{sourceType:'restaurant_order',sourceId:order,reason:'Prueba'}],['POST','/api/inventory/pending-consumptions/x/retry',{}],['PUT',`/api/inventory/items/${item}/unit-conversions`,{conversions:[]}]] as const)expect((await request(method,path,body)).status).toBe(403);});
 it('Restaurant consulta sin costos y opera, pero no modifica catálogo ni anula; SPA solo consulta',async()=>{
  role='restaurant';
  const list=await request('GET','/api/inventory/items');expect(list.status).toBe(200);expect(list.body.find((i:any)=>i.id===item).costPrice).toBeNull();
  expect((await request('POST','/api/inventory/categories',{name:'No autorizado'})).status).toBe(403);
  expect((await request('POST','/api/inventory/source-stock-reversals',{sourceType:'restaurant_order',sourceId:'x',reason:'No autorizado'})).status).toBe(403);
  expect((await request('POST',`/api/inventory/warehouses/${warehouse}/movements`,{itemId:item,movementType:'entrada',quantity:1})).status).toBe(201);
  expect((await request('POST',`/api/inventory/warehouses/${warehouse}/movements`,{itemId:item,movementType:'ajuste',quantity:1})).status).toBe(403);
  expect((await request('POST',`/api/inventory/warehouses/${warehouse}/movements`,{itemId:item,movementType:'entrada',quantity:1,unitCost:100})).status).toBe(403);
  expect((await request('GET',`/api/inventory/items/${item}/price-history`)).status).toBe(403);
  role='spa';expect((await request('GET','/api/inventory/items')).status).toBe(200);
  expect((await request('POST',`/api/inventory/warehouses/${warehouse}/movements`,{itemId:item,movementType:'entrada',quantity:1})).status).toBe(403);
  role='resp_deposito';expect((await request('GET','/api/inventory/items')).body.find((i:any)=>i.id===item).costPrice).toBe('100.00');
 });

});
